scrape_configs:
  - job_name:       'temp'

    static_configs:
        - targets: ['pidock:9091']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 10.16.0.1  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pidock:9116  # SNMP exporter.

  - job_name: 'node'
    static_configs:
        - targets: ['pidock:9100', 'raspberrypi:9100']
